### ISSUE TITLE
Engine.from_cli fails if there is a directory present in the .cache/dagger folder

### ISSUE THREAD

**Issue by tomasol** [kjuulh/dagger-sdk#57]
I have the following in my `.cache/dagger`:
```sh
tree ~/.cache/dagger/
~/.cache/dagger/
├── dagger-0.4.2
├── dagger-0.5.0
└── oci
    └── ingest
```

Running the examples fails on
```
Error: Is a directory (os error 21)
```
Removing the section that calls `std::fs::remove_file` fixes the problem. Not sure why deleting the other files would be necessary.

**Comment by kjuulh** [comment]
Hi @tomasol.

I believe it is a remanant for when I did the initial implementation. That if the version is upgraded the it refreshes the entire directly. This really isn't necessary! 

It would've worked fine if it deleted it properly (though far too wasteful and disruptive for other clients). I've actually written this as a bullet point in the readme.

>  Run in conjunction with golang and other sdks

This was actually the issue I was referring too.

**Comment by kjuulh** [comment]
should be fixed in: https://github.com/kjuulh/dagger-sdk/releases/tag/dagger-sdk-v0.2.21
or rather https://github.com/kjuulh/dagger-sdk/releases/tag/dagger-core-v0.2.10

should be available through a `cargo update`
